# Generated by Django 4.1 on 2023-06-12 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAddress',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.EmailField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
